### ISSUE TITLE
Does not work in windowed mode

### ISSUE THREAD

**Issue by keithrdavis** [bakneko/godot-template#7]
If you set the display server to WINDOW_MODE_WINDOWED, loading a scene shows previous scene in upper right corner when transitioning.

**Comment by keithrdavis** [comment]
The problem was due to the transition scene's position not synced to the main scene's position and canvas items in the main scene drawing before transition starts. Added two lines of code to the transition image script to set the z level high enough to cover the objects in the main scene and moving the transition scene to the correct offset relative to the main scene. This was added to an existing game and the template made some assumptions on the scene configuration.

**Comment by MrBBBaiXue** [comment]
Thanks for providing feedback!
Will investigate this issue when porting this project to 4.0 stable
